# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a023666349d5421e1912abc82d3e1e3d9fc77da6d8906de271b81bf84655a7792273c6c18cf62d177693e73bbc409f5ee2862c96f72f209458cb0ee63a95495

test:
  secret_key_base: e23772de66df47111dc43e43783b8118696ee3c135fe53246f1bf8c94dc96fca09a251f88e0990946996097a3755445fa7e08b8e785e332b8b944b580b9285e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
